/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package otomasyon;

import javax.swing.JOptionPane;

/**
 *
 * @author yusuf
 */
public class musteriMenu extends javax.swing.JFrame {
    
    Otomasyon o;
    String isim;
    double tc;

    /**
     * Creates new form musteriMenu
     */
    public musteriMenu() {
        initComponents();
    }
    
    public musteriMenu(Otomasyon o, double tc, String isim) {
        initComponents();
        this.o = o;
        this.tc = tc;
        this.isim = isim;
        labelTc.setText(String.valueOf(tc));
        labelMusteriIsım.setText(isim);
        bakiyeYaz();
    }

    public void bakiyeYaz() {
        for (int i = 0; i < o.musteriler.size(); i++) {
            if (tc == o.musteriler.get(i).tc) {
                System.out.println(o.musteriler.get(i).tc);
                labelBakiye.setText(String.valueOf(o.musteriler.get(i).para));
                labelLimit.setText(String.valueOf(o.musteriler.get(i).limit));
            }
        
        
            
        }
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        popupMenu1 = new java.awt.PopupMenu();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        paraCek = new javax.swing.JButton();
        faturaOde = new javax.swing.JButton();
        limitGuncelle = new javax.swing.JButton();
        paraTransferi = new javax.swing.JButton();
        paraYatır = new javax.swing.JButton();
        labelBakiye = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        labelMusteriIsım = new javax.swing.JLabel();
        labelTc = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();
        labelLimit = new javax.swing.JLabel();
        jLabel5 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();

        popupMenu1.setLabel("popupMenu1");

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel4.setBackground(new java.awt.Color(51, 0, 102));

        jLabel3.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(102, 255, 255));
        jLabel3.setText("Müşteri Tc");

        jLabel1.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 255, 255));
        jLabel1.setText("Müşteri İsmi");

        paraCek.setBackground(new java.awt.Color(0, 102, 204));
        paraCek.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        paraCek.setForeground(new java.awt.Color(255, 255, 255));
        paraCek.setText("Para Çekme");
        paraCek.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraCekActionPerformed(evt);
            }
        });

        faturaOde.setBackground(new java.awt.Color(0, 51, 204));
        faturaOde.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        faturaOde.setForeground(new java.awt.Color(255, 255, 255));
        faturaOde.setText("Fatura Ödeme");
        faturaOde.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                faturaOdeActionPerformed(evt);
            }
        });

        limitGuncelle.setBackground(new java.awt.Color(0, 102, 204));
        limitGuncelle.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        limitGuncelle.setForeground(new java.awt.Color(255, 255, 255));
        limitGuncelle.setText("Kredi Kartı Limit Güncelle");
        limitGuncelle.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                limitGuncelleActionPerformed(evt);
            }
        });

        paraTransferi.setBackground(new java.awt.Color(0, 102, 204));
        paraTransferi.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        paraTransferi.setForeground(new java.awt.Color(255, 255, 255));
        paraTransferi.setText("Para Transferi");
        paraTransferi.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraTransferiActionPerformed(evt);
            }
        });

        paraYatır.setBackground(new java.awt.Color(0, 102, 204));
        paraYatır.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        paraYatır.setForeground(new java.awt.Color(255, 255, 255));
        paraYatır.setText("Para Yatır");
        paraYatır.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                paraYatırActionPerformed(evt);
            }
        });

        labelBakiye.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        labelBakiye.setForeground(new java.awt.Color(51, 255, 255));

        jLabel2.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(0, 255, 255));
        jLabel2.setText("Bakiye");

        labelMusteriIsım.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        labelMusteriIsım.setForeground(new java.awt.Color(51, 255, 255));

        labelTc.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        labelTc.setForeground(new java.awt.Color(51, 255, 255));

        jLabel4.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(51, 255, 255));
        jLabel4.setText("Limit");

        labelLimit.setFont(new java.awt.Font("Arial Narrow", 1, 24)); // NOI18N
        labelLimit.setForeground(new java.awt.Color(51, 255, 255));

        jLabel5.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jLabel5.setForeground(new java.awt.Color(102, 255, 255));
        jLabel5.setText("Copyright © Mehmet Kemal Savcı 2021");

        jButton1.setBackground(new java.awt.Color(51, 0, 204));
        jButton1.setFont(new java.awt.Font("Arial Narrow", 1, 18)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 255, 255));
        jButton1.setText("Ana Menü");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(22, 22, 22)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel1)
                                .addGap(33, 33, 33)
                                .addComponent(labelMusteriIsım, javax.swing.GroupLayout.PREFERRED_SIZE, 154, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel3, javax.swing.GroupLayout.PREFERRED_SIZE, 130, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addGap(18, 18, 18)
                                .addComponent(labelTc, javax.swing.GroupLayout.PREFERRED_SIZE, 210, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                .addComponent(labelBakiye, javax.swing.GroupLayout.PREFERRED_SIZE, 164, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGap(156, 156, 156)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(paraCek, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paraTransferi, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(paraYatır, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGap(49, 49, 49)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addComponent(jLabel4, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                                .addComponent(labelLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(jLabel2, javax.swing.GroupLayout.PREFERRED_SIZE, 161, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(limitGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faturaOde, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 250, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(0, 76, Short.MAX_VALUE)))))
                .addGap(41, 41, 41))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                .addGap(0, 0, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 283, javax.swing.GroupLayout.PREFERRED_SIZE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(24, 24, 24)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                    .addComponent(jLabel2, javax.swing.GroupLayout.DEFAULT_SIZE, 43, Short.MAX_VALUE)
                    .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.PREFERRED_SIZE, 33, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(labelBakiye, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(labelTc, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addGap(18, 18, 18)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel4Layout.createSequentialGroup()
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 51, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(9, 9, 9)
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(labelLimit, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                                    .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))))
                        .addGap(45, 45, 45)
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                    .addComponent(paraCek, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addComponent(faturaOde, javax.swing.GroupLayout.PREFERRED_SIZE, 62, javax.swing.GroupLayout.PREFERRED_SIZE))
                                .addGap(48, 48, 48)
                                .addComponent(limitGuncelle, javax.swing.GroupLayout.PREFERRED_SIZE, 60, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addComponent(paraTransferi, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.PREFERRED_SIZE, 55, javax.swing.GroupLayout.PREFERRED_SIZE))
                        .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel4Layout.createSequentialGroup()
                                .addGap(44, 44, 44)
                                .addComponent(paraYatır, javax.swing.GroupLayout.PREFERRED_SIZE, 59, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel4Layout.createSequentialGroup()
                                .addGap(36, 36, 36)
                                .addComponent(jButton1, javax.swing.GroupLayout.PREFERRED_SIZE, 67, javax.swing.GroupLayout.PREFERRED_SIZE))))
                    .addComponent(labelMusteriIsım, javax.swing.GroupLayout.PREFERRED_SIZE, 43, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 119, Short.MAX_VALUE)
                .addComponent(jLabel5, javax.swing.GroupLayout.PREFERRED_SIZE, 37, javax.swing.GroupLayout.PREFERRED_SIZE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel4, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel4, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void paraCekActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraCekActionPerformed
        String bakiye = JOptionPane.showInputDialog(null, "Miktar giriniz", JOptionPane.INFORMATION_MESSAGE);
        if (bakiye != null) {
            for (int i = 0; i < o.musteriler.size(); i++) {
                if (Double.parseDouble(labelTc.getText()) == o.musteriler.get(i).tc) {
                    o.paraGuncelle(o.musteriler.get(i).tc, -Double.parseDouble(bakiye));
                    bakiyeYaz();
                }
            }
        }
    }//GEN-LAST:event_paraCekActionPerformed

    private void paraYatırActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraYatırActionPerformed
        String bakiye = JOptionPane.showInputDialog(null, "Miktar giriniz", JOptionPane.INFORMATION_MESSAGE);
        if(bakiye!= null){
        for (int i = 0; i < o.musteriler.size(); i++) {
            if (Double.parseDouble(labelTc.getText()) == o.musteriler.get(i).tc) {
                o.paraGuncelle(o.musteriler.get(i).tc, Double.parseDouble(bakiye));
                bakiyeYaz();
                 
            }
        }
        }
    }//GEN-LAST:event_paraYatırActionPerformed

    private void paraTransferiActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_paraTransferiActionPerformed
        try {
            String tcNo = JOptionPane.showInputDialog(null, "Para transferi yapmak istediğiniz kişinin tc numarasını giriniz", JOptionPane.INFORMATION_MESSAGE);
            String bakiye = JOptionPane.showInputDialog(null, "Miktar giriniz", JOptionPane.INFORMATION_MESSAGE);
            o.paraTransferi(Double.parseDouble(labelTc.getText()), Double.parseDouble(tcNo), Double.parseDouble(bakiye));
            bakiyeYaz();
        } catch (NumberFormatException e) {
            JOptionPane.showMessageDialog(null, "Girilen degerleri kontrol edip tekrar deneyiniz ", " Uyarı ", JOptionPane.WARNING_MESSAGE);
        }
    }//GEN-LAST:event_paraTransferiActionPerformed

    private void faturaOdeActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_faturaOdeActionPerformed
         String bakiye = JOptionPane.showInputDialog(null, " Fatura Borcu Giriniz ", JOptionPane.INFORMATION_MESSAGE);
         if(bakiye != null){
         o.paraGuncelle(tc, -Double.parseDouble(bakiye));
        
         bakiyeYaz();
         }
    }//GEN-LAST:event_faturaOdeActionPerformed

    private void limitGuncelleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_limitGuncelleActionPerformed
       String bakiye = JOptionPane.showInputDialog(null, " Limit Giriniz ", JOptionPane.INFORMATION_MESSAGE);
       if(bakiye != null){
           o.limitGuncelle(tc, Double.parseDouble(bakiye));
           bakiyeYaz();
       }
    }//GEN-LAST:event_limitGuncelleActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        setVisible(false);
        Menu m = new Menu(o);
        m.setVisible(true);
        m.setLocationRelativeTo(null);
    }//GEN-LAST:event_jButton1ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(musteriMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(musteriMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(musteriMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(musteriMenu.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new musteriMenu().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton faturaOde;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JLabel labelBakiye;
    private javax.swing.JLabel labelLimit;
    private javax.swing.JLabel labelMusteriIsım;
    private javax.swing.JLabel labelTc;
    private javax.swing.JButton limitGuncelle;
    private javax.swing.JButton paraCek;
    private javax.swing.JButton paraTransferi;
    private javax.swing.JButton paraYatır;
    private java.awt.PopupMenu popupMenu1;
    // End of variables declaration//GEN-END:variables
}
